name: Docker Build 🚀

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: React Build 
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [21.7.1]

    env:
      APP: coin-community
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-java@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build
          retention-days: 1

  docker:
    name: Build & Deploy Docker Image
    runs-on: ubuntu-latest
    environment: production
    env:
      REPO: ${{ vars.DOCKER_REPO }}
      APP: coin-community    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Retrieve built artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: build

      - name: Building Docker Image
        run: |
          docker login ${{ vars.DOCKER_URL }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t $REPO:${GITHUB_RUN_ID} .
          docker tag $REPO:${GITHUB_RUN_ID} ${{ vars.DOCKER_URL }}/$REPO/$REPO:${GITHUB_RUN_ID}
          docker push ${{ vars.DOCKER_URL }}/$REPO/$REPO:${GITHUB_RUN_ID}
          docker push ${{ vars.DOCKER_URL }}/$REPO/$REPO:latest